"use client";

import Link from "next/link";
import { useRef } from "react";
import { track } from "@/lib/analytics/client";
import { Photo } from "./Photo";
import { Reveal } from "./Reveal";
import { ArrowRight } from "./icons";

const LOOKS = [
  {
    src: "/landing/hero/look-casual.jpg",
    alt: "Casual everyday outfit generated by Lookrdy",
    caption: "Casual Everyday",
    brands: ["ZARA", "NIKE"],
    more: "+4 more",
  },
  {
    src: "/landing/hero/look-smart.jpg",
    alt: "Smart casual outfit generated by Lookrdy",
    caption: "Smart Casual",
    brands: ["COS", "ASOS"],
    more: "+3 more",
  },
  {
    src: "/landing/hero/look-date.jpg",
    alt: "Date night outfit generated by Lookrdy",
    caption: "Date Night",
    brands: ["MANGO", "H&M"],
    more: "+5 more",
  },
];

export function Hero() {
  const railRef = useRef<HTMLDivElement>(null);

  const nudge = () => {
    const rail = railRef.current;
    if (!rail) return;
    // On desktop the rail is a grid; scrolling it does nothing, so fall back to
    // walking the user down to the section that explains the transformation.
    if (rail.scrollWidth > rail.clientWidth) {
      rail.scrollBy({ left: rail.clientWidth * 0.6, behavior: "smooth" });
    } else {
      document
        .getElementById("looks")
        ?.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  };

  return (
    <section className="lnd-hero">
      <div className="lnd-container">
        <div className="lnd-hero__grid">
          <Reveal className="lnd-hero__copy">
            <p className="lnd-eyebrow">Your personal stylist</p>

            <h1 className="lnd-h1">
              Know what to
              <br />
              wear, every time
            </h1>

            <p className="lnd-body">
              Upload one photo and tell us where you&rsquo;re going. Lookrdy
              creates three personalized outfit directions and finds the pieces
              you can actually buy.
            </p>

            <div className="lnd-hero__actions">
              <Link
                href="/create"
                className="lnd-btn lnd-btn--dark"
                onClick={() => track("started")}
              >
                Create my looks
              </Link>
              <a href="#how-it-works" className="lnd-btn lnd-btn--ghost">
                See how it works
              </a>
            </div>

            <p className="lnd-fine">
              First style session free. No account required.
            </p>
          </Reveal>

          <Reveal delay={120}>
            <div className="lnd-hero__rail" ref={railRef}>
              <div className="lnd-shot">
                <div className="lnd-shot__frame">
                  <Photo
                    src="/landing/hero/original.jpg"
                    alt="The original photo a person uploaded"
                    ratio="394 / 884"
                    priority
                  />
                  <span className="lnd-shot__tag">Original Photo</span>
                </div>
              </div>

              {LOOKS.map((look) => (
                <div className="lnd-shot" key={look.caption}>
                  <div className="lnd-shot__frame">
                    <Photo src={look.src} alt={look.alt} ratio="394 / 884" priority />
                  </div>
                  <p className="lnd-shot__caption">{look.caption}</p>
                  <div className="lnd-shot__brands">
                    {look.brands.map((brand) => (
                      <span className="lnd-brand" key={brand}>
                        {brand}
                      </span>
                    ))}
                    <span className="lnd-shot__more">{look.more}</span>
                  </div>
                </div>
              ))}

              <button
                type="button"
                className="lnd-nudge"
                onClick={nudge}
                aria-label="See the generated looks"
              >
                <ArrowRight />
              </button>
            </div>
          </Reveal>
        </div>
      </div>
    </section>
  );
}
