/**
 * TEMPLATE. The claims here must stay true as the pipeline changes — this page
 * is the user-facing description of how looks are generated. Not reviewed by
 * legal counsel.
 */
import type { Metadata } from "next";
import Link from "next/link";
import "../../landing.css";
import { PageShell } from "@/components/landing/PageShell";

export const metadata: Metadata = {
  title: "AI Disclosure — Lookrdy",
  description:
    "How Lookrdy generates outfit visualizations, what they are, and what they are not.",
};

export default function AiDisclosurePage() {
  return (
    <PageShell
      eyebrow="Legal"
      title="AI Disclosure"
      intro="How your looks are generated, what the images are, and where their limits are."
      updated="Last updated 18 August 2026"
    >
      <div className="lnd-prose__note">
        <p>
          <strong>Draft for review.</strong> Confirm each claim below against
          the live generation pipeline before publishing — this page is the
          user-facing statement of how the product works.
        </p>
      </div>

      <h2>The images are visualizations, not photographs</h2>
      <p>
        Every outfit image Lookrdy shows you is generated by an AI model. It is
        an approximation of how a look might sit on you, based on the photo you
        uploaded. It is not a photograph of you wearing those garments, and no
        garment was physically fitted to you.
      </p>

      <h2>What that means in practice</h2>
      <ul>
        <li>
          <strong>Fit is not guaranteed.</strong> How a piece falls on a real
          body depends on cut, fabric and your measurements. Treat the image as
          a styling direction, not a fitting.
        </li>
        <li>
          <strong>Colour and texture drift.</strong> Rendered fabric can differ
          from the real product. Check the retailer’s own photography before
          buying.
        </li>
        <li>
          <strong>Details can be wrong.</strong> Generative models make mistakes
          with hands, logos, buttons and text. If something looks off in the
          image, trust the product listing over the visualization.
        </li>
      </ul>

      <h2>How a look gets made</h2>
      <ul>
        <li>
          You give us a photo, an occasion, preferences and optionally a budget.
        </li>
        <li>
          We search our product catalogue for pieces that fit those constraints
          and are available where you are.
        </li>
        <li>
          We compose three outfits from real products, then generate a
          visualization of each on your photo.
        </li>
        <li>
          Each look is returned with the product list it was built from, priced.
        </li>
      </ul>

      <h2>Product selection is not paid placement</h2>
      <p>
        Retailer matches are examples chosen to fit your brief, not sponsored
        placements. We do not accept payment to place a brand in your results.
        If that ever changes, it will be disclosed clearly on this page and in
        the results themselves.
      </p>

      <h2>Your photo and model training</h2>
      <p>
        Your photo is used to generate your looks. It is not used to train our
        models or a third party’s, it is not published, and it is not sold. The
        detail is in our <Link href="/legal/privacy">Privacy Policy</Link>.
      </p>

      <h2>Human oversight</h2>
      <p>
        Outfit suggestions are generated automatically without a human stylist
        reviewing each one. They are suggestions, not professional advice, and
        the final judgement is yours.
      </p>

      <h2>Getting it wrong</h2>
      <p>
        If a visualization misrepresents you, shows something inappropriate, or
        a product match is plainly wrong, tell us at{" "}
        <a href="mailto:hello@lookrdy.com">hello@lookrdy.com</a>. Reports of
        harmful or misleading output are prioritised.
      </p>
    </PageShell>
  );
}
